version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "okkam"
      POSTGRES_USER: "okkam"
      POSTGRES_PASSWORD: "okkam"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./data/OKKAM_Middle Python Developer_data.csv:/etc/OKKAM_Middle Python Developer_data.csv
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U okkam",]
      interval: 5s
      timeout: 60s
      retries: 20
  app:
    environment:
      OKKAM_TEST_APP_DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    build: okkam_test_app
    ports:
      - "80:8080"
